### PR TITLE
update to 1.21

### PR DESCRIPTION
**Pull request by CrazyHPi**
- Update to Minecraft 1.21
- Change masa's mod depend to jitpack, since newer version of the mod is maintained by [Sakura Ryoko](https://github.com/sakura-ryoko)
- Fix stacking shulker box compact, adapt to [carpet update](https://github.com/gnembon/fabric-carpet/commit/a0bd6e22acaf6856ab5a246df011bd3a55f4ac3f)

### CODE REVIEW

**Comment by CrazyHPi** [comment]
In case anyone need the mod right now: https://github.com/CrazyHPi/itemscroller-crafting-fix/releases/tag/1.2.8.121

**Comment by MrPryor** [comment]
> In case anyone need the mod right now: https://github.com/CrazyHPi/itemscroller-crafting-fix/releases/tag/1.2.8.121

Hey! The Masscrafting crashs the game after updating to the lastest MaLiLib.

https://mclo.gs/JhMJtlL

**Comment by CrazyHPi** [comment]
> > In case anyone need the mod right now: https://github.com/CrazyHPi/itemscroller-crafting-fix/releases/tag/1.2.8.121
> 
> Hey! The Masscrafting crashs the game after updating to the lastest MaLiLib.
> 
> https://mclo.gs/JhMJtlL

Cannot reproduce, it is not malilib and itenscroller's problem.

However, according to the log you provided, this could be a compatibility issue with FANCYMENU.

**Comment by xSparfuchs** [comment]
Mass crafting is significantly slower than in the 1.20.4 version.

**Pull request merged**
